const express=require('express')
const router = express.Router();
const stripe = require('stripe')('sk_test_51IW3v2HgoHB9Ej2a5OKHNv0zC4tppnxGxadaMOZ02IoCJ12E8iJUNVgvOpCHWYnabzrshwQZwjji547B2bZ0LPVx00VaJNfzIA');
const { v4: uuidv4 } = require('uuid');


router.post('/', async (req, res,next) => {
    
    const { email,product , authToken } = req.body;
    const { token } = authToken;
    const { card } = token;

    console.log(card);


  
    console.log("============================================== payment initiate =======================")

 
    const userProduct = product 

    // unique ID generated by client
     const idempotencyKey = uuidv4()

     try {
         const customer = await stripe.customers.create({
             email: email,
             source: token.id
         })

         console.log('Customer Created.....')
         console.log(customer)
         
         const response = await stripe.charges.create({
             amount: userProduct.amount * 100,
             currency: 'INR',
             customer: customer.id,
             receipt_email: email,
             description: userProduct.description,
             shipping: {
                 name: card.name,
                 address: {
                     line1: "Mumbai",
                     country: card.address_country,
                  }
             }
     
         },{ idempotencyKey: idempotencyKey})

         console.log("charge response")
         console.log(response)
           
         
      
         res.json(response)
         
     } catch (err) {
         console.log("=========================================== error ==========================")
        console.log(err)
        res.json(err)
     }
  
})


module.exports =router;





